spring:
  application:
    name: WookieBooks
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false

app:
  secret:
    key: ${JWT_SECRET_KEY:defaultDevSecretKeyForLocalDevelopmentOnly}
  token:
    expiration: ${JWT_EXPIRATION:360000}
  restricted:
    username: ${RESTRICTED_USERNAME:DarthVader}

server:
  port: ${PORT:8083}
