INSERT INTO books (author, description, genre, title) VALUES
                                                          ('George Orwell', 'A dystopian novel about totalitarian control and surveillance.', 'Fiction', '1984'),
                                                          ('J.K. Rowling', 'A young wizard discovers his magical heritage and attends Hogwarts.', 'Fantasy', 'Harry Potter and the Sorcerer''s Stone'),
                                                          ('J.R.R. Tolkien', 'A hobbit embarks on a journey to destroy a powerful ring.', 'Fantasy', 'The Lord of the Rings'),
                                                          ('Jane Austen', 'A classic romance exploring manners, upbringing, and marriage.', 'Romance', 'Pride and Prejudice'),
                                                          ('Dan Brown', 'A symbologist uncovers secrets hidden in famous artworks.', 'Thriller', 'The Da Vinci Code'),
                                                          ('Yuval Noah Harari', 'A brief history of humankind from evolution to modern times.', 'Education', 'Sapiens'),
                                                          ('Mark Twain', 'The adventures of a young boy growing up along the Mississippi River.', 'Fiction', 'The Adventures of Tom Sawyer'),
                                                          ('Stephen King', 'A horror thriller about a haunted hotel and a family trapped inside.', 'Thriller', 'The Shining'),
                                                          ('Nicholas Sparks', 'A romantic story of love, loss, and destiny.', 'Romance', 'The Notebook'),
                                                          ('Paulo Coelho', 'A philosophical tale about following your dreams.', 'Fiction', 'The Alchemist'),
                                                          ('C.S. Lewis', 'Children discover a magical world through a wardrobe.', 'Fantasy', 'The Chronicles of Narnia'),
                                                          ('Agatha Christie', 'A detective solves a murder mystery on a train.', 'Thriller', 'Murder on the Orient Express'),
                                                          ('F. Scott Fitzgerald', 'A tragic story of wealth, love, and the American dream.', 'Fiction', 'The Great Gatsby'),
                                                          ('Leo Tolstoy', 'A complex novel of love, betrayal, and Russian society.', 'Romance', 'Anna Karenina'),
                                                          ('Robert Kiyosaki', 'Lessons about financial education and wealth building.', 'Education', 'Rich Dad Poor Dad'),
                                                          ('Suzanne Collins', 'A dystopian survival game where only one can win.', 'Fantasy', 'The Hunger Games'),
                                                          ('Arthur Conan Doyle', 'Sherlock Holmes investigates mysterious cases.', 'Thriller', 'The Hound of the Baskervilles'),
                                                          ('Erich Maria Remarque', 'A soldier reflects on the horrors of war.', 'Fiction', 'All Quiet on the Western Front'),
                                                          ('E.L. James', 'A controversial romance novel exploring complex relationships.', 'Romance', 'Fifty Shades of Grey'),
                                                          ('Malcolm Gladwell', 'Explores factors that contribute to high levels of success.', 'Education', 'Outliers'),
                                                          ('Herman Melville', 'A sea captain obsessively hunts a giant whale.', 'Fiction', 'Moby Dick'),
                                                          ('Bram Stoker', 'A gothic horror story about the vampire Dracula.', 'Thriller', 'Dracula'),
                                                          ('J.D. Salinger', 'A teenager struggles with identity and alienation.', 'Fiction', 'The Catcher in the Rye'),
                                                          ('Stephen Hawking', 'An introduction to cosmology and black holes.', 'Education', 'A Brief History of Time'),
                                                          ('Emily Brontë', 'A passionate and tragic love story set on the moors.', 'Romance', 'Wuthering Heights');